# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dd9bcb7ea84cbd2e419ec87f1d09dd3f9f2897a01c79dd9588133c572ad1ee2954dad102a5dddd6896882f72e98256a7ec07c756ff87fc78aff9b65f2de2e237

test:
  secret_key_base: e84f88b32696a0b3edbec75dd04d21ed6ac9583cc9187d24a7c18bedfb75c9f6c21f90373aac47302b259a3d541b509adbd63ebbfeece60c8e0859b03b328c11

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
